######################################################
# Config File including all arguments for training and evaluation of any model
# "training": general training arguments
# "evaluation:" general evaluation arguments
# "model_name:" arguments for initializing specific model
#

args:
  training:
    random_state: 1337
    n_users: 10000
    n_movies: 1000
    test_set_size: 0.1
    verbose: True

  evaluation:
    pass: Null

  SVDplusplus: #Achieves about 1.15 score
    n_factors: 5
    lr_all: 0.002
    n_epochs: 100
    reg_all: 0.04

  SVDsimple: #Achieves about 1.14 score
    n_factors: 30
    lr_all: 0.002
    n_epochs: 20
    reg_all: 0.1

  KNN: #Achieves about 1.13 score
    k: 150
    min_k: 20
    sim_options: {"name": "pearson_baseline", "shrinkage": 10}

  NeuralCF: #Achieves about 1.03 score
    model_type: "NeuMF"
    n_factors: 4
    layer_sizes: [16,8,4]
    n_epochs: 100
    batch_size: 256
    learning_rate: 0.0015

  BFM: #Achieves about 0.96 score
    algorithm: "oprobit"  
    variational: False    
    iteration: 3500
    dimension: 24       
    use_iu: True          
    use_ii: True 
