######################################################
# Config File including all arguments for training and evaluation of any model
# "training": general training arguments
# "evaluation:" general evaluation arguments
# "model_name:" arguments for initializing specific model
#

#TODO: Currently parameters are default values
#   We should use existing values from prior students and perform gridsearch with similar working 
#   values to confirm their values or find even better ones.

args:
  training:
    random_state: 1337
    n_users: 10000
    n_movies: 1000
    test_set_size: 0.1
    verbose: False

  evaluation:
    pass: Null

  SVDplusplus: #Achieves about 1.15 score
    n_factors: 3
    lr_all: 0.003
    n_epochs: 100
    reg_all: 0.05

  SVDsimple: #Achieves about 1.14 score
    n_factors: 30
    lr_all: 0.002
    n_epochs: 20
    reg_all: 0.1

  KNN: #Achieves about 1.13 score
    k: 150
    min_k: 20
    sim_options: {"name": "pearson_baseline", "shrinkage": 10}

  NeuralCF:
    model_type: "NeuMF"
    n_factors: 5
    layer_sizes: [16,8,4]
    n_epochs: 60
    batch_size: 256
    learning_rate: 0.001
