# Yaml file containing the parameters for performing grid-search for each model

SVDplusplus:
  n_factors: [3, 10]
  lr_all: [0.003, 0.005, 0.007]
  n_epochs: [10, 50, 100]
  reg_all: [0.01, 0.05, 0.08]

SVDsimple:
  n_factors: [3, 15]
  lr_all: [0.003, 0.005, 0.007]
  n_epochs: [10, 50, 100]
  reg_all: [0.01, 0.05, 0.08]

KNN:
  k: [40, 60, 100, 150]
  min_k: [5, 10, 20]
  sim_options: [{"name": "pearson_baseline", "shrinkage": 1}, {"name": "pearson_baseline", "shrinkage": 10}]

  NeuralCF:
    model_type: ["NeuMF"]
    n_factors: [4]
    layer_sizes: [[16,8,4]]
    n_epochs: [50]
    batch_size: [256]
    learning_rate: [0.001]